### ISSUE TITLE
ERROR in inference

### ISSUE THREAD

**Issue by syj2908** [YouAreSpecialToMe/QST#4]
hi, i trained llama-hf-7b and met the error below in running chatbot.py. Is there any solution?
```
Traceback (most recent call last):
  File "chatbot_sample.py", line 114, in <module>
    outputs = model.generate(bot_input_ids, do_sample=True,
  File "/home/w50037733/anaconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/w50037733/anaconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 1648, in generate
    return self.sample(
  File "/home/w50037733/anaconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 2730, in sample
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [4,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [5,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [6,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
    outputs = self(
  File "/home/w50037733/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/SSD7/personal/shiyanjiang.syj/QST/modeling_llama_qst.py", line 1358, in forward
    outputs = self.model(
  File "/home/w50037733/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/SSD7/personal/shiyanjiang.syj/QST/modeling_llama_qst.py", line 1014, in forward
    qst_layer_outputs = self.qst_layers[idx](
  File "/home/w50037733/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/SSD7/personal/shiyanjiang.syj/QST/modeling_llama_qst.py", line 442, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/w50037733/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/SSD7/personal/shiyanjiang.syj/QST/modeling_llama_qst.py", line 368, in forward
    raise ValueError(
ValueError: Attention mask should be of size (1, 1, 1, 1), but is torch.Size([1, 1, 1, 587])
```

**Comment by YouAreSpecialToMe** [comment]
Hi, I've updated the generation code. Now it works well on my side, can you update the code and try it again?

**Comment by syj2908** [comment]
It works fine now. Thanks!
